version: '3.0'
services:
  elasticsearch:
    container_name: elasticsearch
    build: env/elasticsearch
    volumes:
        - ./data/elasticsearch:/usr/share/elasticsearch/data
    ports:
        - 9200:9200
    expose:
        - 9300

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:6.2.2
    ports:
        - 5601:5601

  online:
    container_name: online
    build: env/online/.
    links:
      - elasticsearch
    ports:
      - "5000:5000"
    volumes:
      - ./online:/home
    command: flask run --host 0.0.0.0 --port 5000

  batch:
    container_name: batch
    build: env/batch/.
    links:
      - elasticsearch
      - online
    volumes:
      - ./batch:/home
